### ISSUE TITLE
Update configurations to module load the model 

### ISSUE THREAD

**Issue by jo-basevi** [ACCESS-NRI/access-om2-configs#142]
Currently the payu configuration executables use a full path:

https://github.com/ACCESS-NRI/access-om2-configs/blob/fce24e35bdf35720a15b6b03fa3616d3486f50b4/config.yaml#L33

Payu now supports finding model executables from loaded model modules. In `access-esm1.5-configs` configurations have already set this up (see https://github.com/ACCESS-NRI/access-esm1.5-configs/blob/475e222cd37aa3e0bdec384058cf2684e632dd7b/config.yaml#L24-L29)

For example the `config.yaml` might look something like the following:
```
# Modules for loading model executables
modules:
  use:
      - /g/data/vk83/modules
  load:
      - access-om2/2024.03.0
```

The fullpath executables would be just the filename, e.g.:
```
exe: yatm.exe
```

The QA tests were updated to check the executable paths (https://github.com/ACCESS-NRI/model-config-tests/issues/18) so the version of `model-config-tests` will need to be updated in CI configuration file: https://github.com/ACCESS-NRI/access-om2-configs/blob/e8ac85429765166c80fece3cea26fcac2325fd57/config/ci.json#L21
